= WWW(wow-welcome-webtoon) API Document
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toc-title: 목차
:toclevels: 2
:sectlinks:
//:operation-curl-request-title: Example request
//:operation-http-response-title: Example response

[[introduction-platform]]
= 플랫폼 서버

Platform Server API 문서

현재 플랫폼 서버 port는 8082를 사용합니다.


[[Comments]]
== 댓글 시스템

[[Comments-get]]
=== GET 댓글 목록 조회
- 해당 회차(ep_idx)의 댓글을 페이지(page)를 구분하여 조회합니다.
- 요청 가능한 페이지 범위내에서 한 페이지당 최대 15개의 댓글을 조회합니다.
- page 값이 0이하 혹은 총 페이지 수보다 크면 요청 실패 하여 23 code를 반환 합니다.
- idx(댓글 테이블 기본키)의 내림차순으로 정렬되어 출력되기 때문에 응답되어 온 comments의 인덱스의 숫자가 클수록 최신 댓글 입니다.

operation::comment-controller-test/get-comments[snippets='http-request,path-parameters,request-parameters,http-response,response-fields']


=== GET 베스트 댓글 목록 조회
- 해당 회차(ep_idx)의 댓글 중 베스트 댓글 최대 5개 까지 조회 합니다.
- 좋아요 수와 싫어요 수의 차이가 5이상의 댓글 중에서 좋아요 수와 싫어요 수의 차이가 가장 큰 순으로 조회합니다.
- 조회 조건이 맞지 않은 경우 "베스트 댓글 목록 조회" 요청은 성공 했으나 댓글이 0개가 반환될 수 있습니다.

operation::comment-controller-test/get-best-commnets[snippets='http-request,path-parameters,http-response,response-fields']


=== GET 마이페이지 내가 쓴 댓글 조회
- 내(User)가 쓴 댓글을 페이지(page)를 구분하여 조회합니다.
- 요청 가능한 페이지 범위내에서 한 페이지당 최대 10개의 댓글을 조회합니다.
- page 값이 0이하 혹은 총 페이지 수보다 크면 요청 실패 하여 23 code를 반환 합니다.
- idx(댓글 테이블 기본키)의 내림차순으로 정렬되어 출력되기 때문에 응답되어 온 comments의 인덱스의 숫자가 클수록 최신 댓글 입니다.

operation::comment-controller-test/get-my-page-comments[snippets='http-request,request-headers,request-parameters,http-response,response-fields']


=== POST 댓글 등록
- 해당 회차(ep_idx)에 대한 댓글을 등록합니다.

operation::comment-controller-test/insert-comment[snippets='http-request,request-headers,path-parameters,request-fields,http-response,response-fields']


=== POST 댓글 좋아요 요청
- 해당 댓글(cmt_idx)에 대해 좋아요 요청을 합니다.
- 이전의 좋아요를 요청한 내역이 없으면 새롭게 좋아요 요청을 저장하고 좋아요 수를 1 증가합니다.
- 이전의 좋아요를 요청한 내역이 있으면 내역을 삭제하고 좋아요 수를 1 감소합니다.

operation::comment-controller-test/request-comment-like[snippets='http-request,request-headers,path-parameters,http-response,response-fields']


=== POST 댓글 싫어요 요청
- 해당 댓글(cmt_idx)에 대해 싫어요 요청을 합니다.
- 이전의 싫어요를 요청한 내역이 없으면 새롭게 싫어요 요청을 저장하고 싫어요 수를 1 증가합니다.
- 이전의 싫어요를 요청한 내역이 있으면 내역을 삭제하고 싫어요 수를 1 감소합니다.

operation::comment-controller-test/request-comment-dislike[snippets='http-request,request-headers,path-parameters,http-response,response-fields']


=== DEL 댓글 삭제
- 해당 댓글(cmt_idx)을 삭제합니다.

operation::comment-controller-test/delete-comment[snippets='http-request,request-headers,path-parameters,http-response,response-fields']


== 별점 시스템

=== POST 회차 별점 주기(등록)
- 해당 회차(ep_idx)에 대한 별점을 등록합니다.
- 별점 등록이 성공하면 등록한 점수(rating)를 반영하여 해당 회차와 웹툰에 대한 평점을 업데이트 합니다.
- 해당 회차에 대해 계산된 별점 평점(rating)과 참여자 수(person_total)를 반환 합니다.

operation::star-rating-controller-test/insert-star-rating[snippets='http-request,request-headers,path-parameters,request-fields,http-response,response-fields']
